name: Das große Axelrod Turnier

on:
  workflow_dispatch:

jobs:
  run-tournament:
    runs-on: ubuntu-latest
    steps:
      - name: Code ausleihen
        uses: actions/checkout@v4

      - name: Python vorbereiten
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System-Abhängigkeiten und Axelrod installieren
        run: |
          pip install --upgrade pip setuptools wheel
          # Unverzichtbar für die KIs im großen Feld:
          pip install numpy scipy
          pip install -e .

      - name: Turnier starten
        run: python Axelrod/turniertestvoll.py
